---
# Bootstrap a new Galera cluster
- import_playbook: flush_jumphost_key.yaml

- name: install software
  hosts: galera
  roles:
    - opentelekomcloud.server_common
    - opentelekomcloud_infra.galera

- name: start cluster
  hosts: galera
  become: yes
  tasks:
    - systemd:
        service: mariadb
        state: started
        enabled: yes
